version: '3'

services:
    mysql:
        image: mysql:5.6.40
        ports:
            - "3306:3306"
        environment:
            MYSQL_USER: isucari
            MYSQL_PASSWORD: isucari
            MYSQL_DATABASE: isucari
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
